- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-09d07490acc07ecdc
    zone_id: "Z09862333DG9EIMMVCYEW"
    domain-name: "userbolla.store"
    instances: 
    - mongodb
    # - redis
    # - mysql
    # - 
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      instance_type: t3.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
      tags:
        Name: "{{item}}"
    loop: "{{instances}}"
    register: ec2_output
  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ec2_output}}"